config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/movies' => 'movies#index', as: :home
  # get '/movies/:id' => 'movies#show', as: :movie
  # get '/actors' => 'actors#index'
  # get '/movies/new' => 'movies#new'
  # get '/actors/:id' => 'actors#show', as: :actor
  #
  #
  # post 'movies' => 'movies#create'
  root 'movies#home', as: 'home'
  resources :movies
  resources :actors

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :sessions

end

app/models/actor.rb
class Actor < ApplicationRecord

  has_many :parts
  has_many :movies, through: :parts

  mount_uploader :image, ImageUploader

  validates :first_name, :last_name,  presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :parts
  has_many :actors, through: :parts

  mount_uploader :image, ImageUploader

end

app/models/part.rb
class Part < ApplicationRecord

  belongs_to :movie
  belongs_to :actor

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  mount_uploader :image, ImageUploader

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to '/actors'
    else
      render 'new'
    end
  end

  def edit
    @actor = Actor.find(params[:id])
  end

  def update
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(actor_params)
      redirect_to(:action => 'show', :id => @actor.id)
    else
      render 'edit'
    end
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  private
  def actor_params
    params.require(:actor).permit(:first_name, :last_name, :image, :bio)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  #before_action :require_user, only: [:index, :show]

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to '/movies'
    else
      render 'new'
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to(:action => 'show', :id => @movie.id)
    else
      render 'edit'
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :release_year, :image, :plot)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to home_url
    else
      #flash.now.alert = "Email or password is invalid"
      #redirect_to '/login'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :town, :email, :password, :image)
    end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/edit.html.erb
<hr>

<%= form_for(@actor) do |a| %>
    <%= a.label :first_name %>
    <%= a.text_field(:first_name, {:class => 'form-control'})%><br>

    <%= a.label :last_name %>
    <%= a.text_field(:last_name, {:class => 'form-control'})%><br>

    <%= a.label :description %>
    <%= a.text_area(:bio, {:class => 'form-control'})%><br>

    <%= a.label :image %>
    <%= a.file_field :image %><br>

    <%= a.submit({:class => 'btn btn-primary'}) %>

<% end %>

app/views/actors/index.html.erb
<hr>
<p>
  <%= image_tag("actors.jpg", width: '1057px')%>
  <br>
</p>
<hr>

<div class="container" >
      <% @actors.each do |actor| %>
                <div class="box">
                  <p><%= image_tag actor.image, size: "300x200" %></p>
                  <div style="height: 40px; width: auto">
                  <h3><%= actor.first_name %>  <%= actor.last_name %></h3>
                  </div>
                  <div style="height: 90px; width: auto">
                  <p><%= actor.bio %></p>
                  </div>
                  <%= link_to "Read more", actor_path(actor), :class => 'btn btn-primary' %>
                </div>
      <% end %>
</div>

app/views/actors/new.html.erb
<div class="form">
<h1>Add new Actors</h1><br>

<hr>

<%= form_for(@actor) do |a| %>
    <%= a.label :first_name %>
    <%= a.text_field(:first_name, {:placeholder => "First name",:class => 'form-control'})%><br>

    <%= a.label :last_name %>
    <%= a.text_field(:last_name, {:placeholder => "Last name",:class => 'form-control'})%><br>

    <%= a.label :description %>
    <%= a.text_area(:bio, {:placeholder => "Enter small description",:class => 'form-control'})%><br>

    <%= a.label :image %>
    <%= a.file_field :image %><br>

    <%= a.submit({:class => 'btn btn-primary'}) %>

<% end %>
</div>

app/views/actors/show.html.erb
<hr>
<div class="container" >
    <div class="center-content">
        <p><%= image_tag @actor.image, size: "700x250" %></p>
        <h3><%= @actor.first_name %>  <%= @actor.last_name %></h3>
        <p><%= @actor.bio %></p>
    </div>
    <div style="text-align: center">
        <%= link_to "Edit Details", edit_actor_path(@actor), :class => 'btn btn-warning'%>
        <%= link_to "Delete Actor", actor_path(@actor), method: :delete,
                    data: {confirm: 'Are you sure?'},:class => 'btn btn-danger'%>
    </div>
    <hr>
    <h2>Movies</h2>
    <hr>
    <% @movies.each do |movie|%>
        <div class="box">
            <div class="center-content">
              <%= image_tag movie.image, size: "200x150" %>
              <h3><%= movie.title %></h3>
              <h5><%= movie.release_year %></h5>
              <p><%= movie.plot %></p>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  </head>

  <body>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MovieX-tra</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">

        <ul class="nav navbar-nav">
        <li > <%= link_to "        " %></li>
        </ul>

        <ul class="nav navbar-nav">
          <li ><%= link_to "Home", home_path %></li>
        </ul>

        <ul class="nav navbar-nav">
          <li ><%= link_to "Movies", movies_path %></li>
        </ul>

        <ul class="nav navbar-nav">
          <li ><%= link_to "Actors", actors_path %></li>
        </ul>

        <ul class="nav navbar-right">
          <li ><%= link_to "Create Movie", new_movie_path %></li>
        </ul>

        <ul class="nav navbar-right">
          <li ><%= link_to "Create Actor", new_actor_path %></li>
        </ul>
        <!--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->


            <% if current_user %>
                <ul class="nav navbar-right">
                  <li><%= current_user.email %></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>

            <% else %>
              <ul class="nav navbar-right">
                  <li><%= link_to "Login", 'login' %></a></li>
              </ul>
              <ul class="nav navbar-right">
                  <li><%= link_to "Signup", 'signup' %></a></li>
              </ul>
            <% end %>

        <!--xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-->

      </div><!--/.nav-collapse -->
    </div>
  </nav>


  <div class="container">

  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= yield %>
  </div>
  </body>
</html>

app/views/movies/edit.html.erb
<%= form_for(@movie) do |m| %>

<%= m.label(:title_of_movie) %>
<%= m.text_field(:title, {:class => 'form-control'})%><br>

<%= m.label(:released_year)%>
<%= m.text_field(:release_year, {:class => 'form-control'}) %><br>

<%= m.label(:plot)%>
<%= m.text_area(:plot, {:class => 'form-control'}) %><br>

<%= m.label(:image)%>
<%= m.file_field :image %><br>

<%= m.submit({:class => 'btn btn-primary'}) %>

<% end %>

app/views/movies/home.html.erb
<h1>Home page</h1>

app/views/movies/index.html.erb
<hr>

<div class="container" >

  <p>
    <%= image_tag("films.jpg", width: '1057px')%>
    <br>
  </p>
  <hr>

  <% @movies.each do |movie|%>
      <div class="box" >
        <p><%= image_tag movie.image, size: "300x200" %></p>
        <div style="height: 60px; width: auto">
          <h2><%= movie.title %></h2>
        </div>
        <p><strong>Released on:</strong> <%= movie.release_year %></p>
        <div style="height: 80px; width: auto">
          <p><%= movie.plot %></p>
        </div>
        <%= link_to "Read more", movie_path(movie), :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="form">
<h1>Add new Movie</h1><br>

<hr>

<%= form_for(@movie) do |m| %>

    <%= m.label(:title_of_movie) %>
    <%= m.text_field(:title, {:placeholder => "Enter movie name",:class => 'form-control'})%><br>

    <%= m.label(:released_year)%>
    <%= m.text_field(:release_year, {:placeholder => "Enter released year",:class => 'form-control'}) %><br>

    <%= m.label(:plot)%>
    <%= m.text_area(:plot, {:placeholder => "Enter small description",:class => 'form-control'}) %><br>

    <%= m.label(:image)%>
    <%= m.file_field :image %><br>

    <%= m.submit({:class => 'btn btn-primary'}) %>

<% end %>

</div>

app/views/movies/show.html.erb
<hr>
<div class="container" >
    <div class="center-content">
        <p><%= image_tag @movie.image, size: "700x250" %></p>
        <h3><%= @movie.title %></h3><br>
        <h5><%= @movie.release_year %></h5><br>
        <p><%= @movie.plot %></p><br>
    </div>
    <div style="text-align: center">
      <%= link_to "Edit Details", edit_movie_path(@movie), :class => 'btn btn-warning'%>
      <%= link_to "Delete Movie", movie_path(@movie), method: :delete,
                  data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger'%>
    </div>
  <hr>
  <h2>Cast</h2>
  <hr>
  <div class="center-content">
      <% @actors.each do |actor| %>
          <div class="box">
            <%= image_tag actor.image, size: "200x150" %>
            <h4><%= actor.first_name %>  <%= actor.last_name %></h4>
            <p><%= actor.bio %></p>
          </div>
      <% end %>
  </div>
</div>

app/views/users/new.html.erb
  <div class="container">
    <div class="form">

      <h1>Register now</h1>
      <hr>

      <%= form_for(@user) do |f|%>
          <%= f.label(:first_name) %>
          <%= f.text_field :first_name, :placeholder => "Enter your first name", class: "form-control"%><br>

          <%= f.label(:last_name) %>
          <%= f.text_field :last_name, :placeholder => "Enter your last name", class: "form-control"%><br>

          <%= f.label(:town) %>
          <%= f.text_field :town, :placeholder => "Where are you from", class: "form-control"%><br>

          <%= f.label(:e_mail) %>
          <%= f.email_field :email, :placeholder => "example@mail.com", class: "form-control"%><br>

          <%= f.label(:password) %>
          <%= f.password_field :password, :placeholder => "Enter password", class: "form-control" %><br>

          <%= f.label(:image) %>
          <%= f.file_field :image%><br>

          <%= f.submit "Create an account", class: "btn btn-primary" %>

      <% end %>

    </div>
  </div>